"""
document_agent/tools.py — All 10 tool functions for the Document Agent.

Tools are grouped into two categories:
  - Template tools (generate_cv, generate_cover_letter, generate_proposal,
    generate_report, generate_invoice, generate_email)
  - Intelligence tools (load_and_summarize, answer_from_document,
    edit_and_improve, export_as_markdown)

All functions return strings only. Module-level state is shared across calls.
"""

import re
import uuid
from datetime import datetime, timedelta

# ---------------------------------------------------------------------------
# Module-level shared state
# ---------------------------------------------------------------------------

_document = {
    "filename": "",
    "content": "",
    "loaded": False,
}

_last_generated = {
    "type": "",
    "content": "",
}


# ---------------------------------------------------------------------------
# Tool 1 — generate_cv
# ---------------------------------------------------------------------------

def generate_cv(
    full_name: str,
    email: str,
    phone: str,
    location: str,
    job_title: str,
    summary: str = "",
    experience: str = "",
    education: str = "",
    skills: str = "",
    languages: str = "",
) -> str:
    """Generate a professional CV / Resume.

    Creates a fully formatted CV with all standard sections. Optional fields
    are pre-filled with intelligent placeholder text if not provided.

    Args:
        full_name:  Candidate's full name.
        email:      Candidate's email address.
        phone:      Candidate's phone number.
        location:   Candidate's city / country.
        job_title:  Target job title / current role.
        summary:    Professional summary paragraph.
        experience: Work experience block (multi-line).
        education:  Education block (multi-line).
        skills:     Comma-separated skills list.
        languages:  Languages and proficiency levels.

    Returns:
        Formatted CV as a string.
    """
    global _last_generated

    if not summary:
        summary = (
            f"Results-driven {job_title} with X+ years of experience in [industry]. "
            "Passionate about [key area]. Seeking to [goal]."
        )
    if not experience:
        experience = (
            f"[Company Name] — [City] | [Start] – [End]\n"
            f"  {job_title}\n"
            "  • [Key achievement or responsibility]\n"
            "  • [Key achievement or responsibility]\n"
            "  • [Key achievement or responsibility]"
        )
    if not education:
        education = (
            "[Degree Name] in [Field of Study]\n"
            "  [University Name] — [City] | [Year]"
        )
    if not skills:
        skills = "[Skill 1], [Skill 2], [Skill 3], [Skill 4]"
    if not languages:
        languages = "English (Fluent)"

    date_str = datetime.now().strftime("%B %d, %Y")
    divider = "═" * 52
    thin = "─" * 52

    output = f"""{divider}
                   {full_name.upper()}
{divider}
{job_title}
📧 {email}  |  📞 {phone}  |  📍 {location}
{thin}

PROFESSIONAL SUMMARY
{thin[:20]}
{summary}

WORK EXPERIENCE
{thin[:15]}
{experience}

EDUCATION
{thin[:9]}
{education}

SKILLS
{thin[:6]}
{skills}

LANGUAGES
{thin[:9]}
{languages}

{divider}
Generated by Hyperzod Document Agent
{date_str}
{divider}"""

    _last_generated["type"] = "cv"
    _last_generated["content"] = output
    return output


# ---------------------------------------------------------------------------
# Tool 2 — generate_cover_letter
# ---------------------------------------------------------------------------

def generate_cover_letter(
    full_name: str,
    email: str,
    phone: str,
    job_title: str,
    company_name: str,
    hiring_manager: str = "Hiring Manager",
    key_skills: str = "",
    why_company: str = "",
    years_experience: str = "several",
) -> str:
    """Generate a professional cover letter.

    Args:
        full_name:        Applicant's full name.
        email:            Applicant's email address.
        phone:            Applicant's phone number.
        job_title:        Position being applied for.
        company_name:     Target company name.
        hiring_manager:   Recipient name or title.
        key_skills:       Comma-separated key skills to highlight.
        why_company:      Reason for interest in this specific company.
        years_experience: Years of experience as a string.

    Returns:
        Formatted cover letter as a string.
    """
    global _last_generated

    if not key_skills:
        key_skills = "problem-solving, communication, and leadership"
    if not why_company:
        why_company = "its reputation for innovation and excellence"

    date_str = datetime.now().strftime("%B %d, %Y")
    thin = "─" * 52

    output = f"""{full_name}
{email} | {phone}
{date_str}

Dear {hiring_manager},

I am writing to express my strong interest in the {job_title} position at {company_name}. \
With {years_experience} years of experience and a proven track record in {key_skills}, \
I am confident in my ability to make a meaningful contribution to your team.

What draws me to {company_name} is {why_company}. I am particularly excited about the \
opportunity to bring my expertise in {key_skills} to help drive your mission forward.

Throughout my career, I have consistently delivered results by [specific achievement — \
customize this section]. I thrive in environments that challenge me and reward dedication, \
creativity, and collaboration.

I would welcome the opportunity to discuss how my background, skills, and enthusiasm align \
with the needs of {company_name}. Thank you for considering my application. \
I look forward to speaking with you.

Warm regards,
{full_name}
{email} | {phone}

{thin}
Generated by Hyperzod Document Agent
{date_str}"""

    _last_generated["type"] = "cover_letter"
    _last_generated["content"] = output
    return output


# ---------------------------------------------------------------------------
# Tool 3 — generate_proposal
# ---------------------------------------------------------------------------

def generate_proposal(
    project_title: str,
    prepared_by: str,
    prepared_for: str,
    problem_statement: str = "",
    proposed_solution: str = "",
    timeline: str = "",
    budget: str = "",
    deliverables: str = "",
) -> str:
    """Generate a professional business proposal.

    Args:
        project_title:      Title of the project or proposal.
        prepared_by:        Name of the person / company submitting.
        prepared_for:       Name of the client / recipient.
        problem_statement:  Description of the problem being solved.
        proposed_solution:  Description of the proposed approach.
        timeline:           Project phases and schedule.
        budget:             Itemized cost breakdown.
        deliverables:       List of expected deliverables.

    Returns:
        Formatted business proposal as a string.
    """
    global _last_generated

    if not problem_statement:
        problem_statement = (
            "[Describe the core problem or opportunity this proposal addresses. "
            "Include context, current pain points, and why action is needed.]"
        )
    if not proposed_solution:
        proposed_solution = (
            "[Describe your solution clearly. Explain the approach, methodology, "
            "and why this solution is the best fit for the problem.]"
        )
    if not timeline:
        timeline = (
            "Phase 1 (Week 1-2): Discovery and Planning\n"
            "Phase 2 (Week 3-6): Development and Execution\n"
            "Phase 3 (Week 7-8): Testing and Delivery"
        )
    if not budget:
        budget = (
            "[Itemize costs clearly. Include labor, materials, tools, "
            "contingency. Provide total investment required.]"
        )
    if not deliverables:
        deliverables = (
            "• [Deliverable 1 — description and format]\n"
            "• [Deliverable 2 — description and format]\n"
            "• [Deliverable 3 — description and format]"
        )

    date_str = datetime.now().strftime("%B %d, %Y")
    ref = f"PROP-{uuid.uuid4().hex[:6].upper()}"
    divider = "═" * 52
    thin = "─" * 52

    output = f"""{divider}
BUSINESS PROPOSAL
{project_title}
{divider}
Prepared by:  {prepared_by}
Prepared for: {prepared_for}
Date:         {date_str}
Reference:    {ref}
{thin}

EXECUTIVE SUMMARY
{thin[:17]}
This proposal outlines a plan to address [core objective] for {prepared_for}. \
{prepared_by} proposes a structured approach that delivers measurable results \
within the agreed timeline and budget.

PROBLEM STATEMENT
{thin[:17]}
{problem_statement}

PROPOSED SOLUTION
{thin[:17]}
{proposed_solution}

DELIVERABLES
{thin[:12]}
{deliverables}

TIMELINE
{thin[:8]}
{timeline}

INVESTMENT
{thin[:10]}
{budget}

TERMS & CONDITIONS
{thin[:18]}
• This proposal is valid for 30 days from the date above.
• A 50% advance is required to commence work.
• Final payment due upon project completion and approval.
• Revisions beyond agreed scope will be quoted separately.

ACCEPTANCE
{thin[:10]}
Signature: _______________________  Date: ___________
Name:      _______________________
Title:     _______________________

{divider}
Generated by Hyperzod Document Agent
{date_str}
{divider}"""

    _last_generated["type"] = "proposal"
    _last_generated["content"] = output
    return output


# ---------------------------------------------------------------------------
# Tool 4 — generate_report
# ---------------------------------------------------------------------------

def generate_report(
    report_title: str,
    prepared_by: str,
    project_name: str = "",
    executive_summary: str = "",
    objectives: str = "",
    methodology: str = "",
    findings: str = "",
    recommendations: str = "",
    conclusion: str = "",
) -> str:
    """Generate a structured project report.

    Args:
        report_title:       Title of the report.
        prepared_by:        Author name.
        project_name:       Associated project name.
        executive_summary:  High-level summary for stakeholders.
        objectives:         Goals and objectives of the project.
        methodology:        Approach and methods used.
        findings:           Key results and observations.
        recommendations:    Suggested next steps or actions.
        conclusion:         Closing remarks.

    Returns:
        Formatted project report as a string.
    """
    global _last_generated

    proj = project_name if project_name else "[Project Name]"
    if not executive_summary:
        executive_summary = "[Provide a high-level summary of the project, its goals, and key outcomes. This section is read by stakeholders who may not read the full report.]"
    if not objectives:
        objectives = "• [Primary objective of the project]\n• [Secondary objective]\n• [Success criteria and KPIs]"
    if not methodology:
        methodology = "[Describe the approach, tools, frameworks, or research methods used to carry out the project.]"
    if not findings:
        findings = "• [Key finding or result 1]\n• [Key finding or result 2]\n• [Key finding or result 3]"
    if not recommendations:
        recommendations = "• [Recommended action 1]\n• [Recommended action 2]\n• [Recommended action 3]"
    if not conclusion:
        conclusion = "[Summarize the overall outcome, lessons learned, and the path forward.]"

    date_str = datetime.now().strftime("%B %d, %Y")
    report_id = f"RPT-{uuid.uuid4().hex[:8].upper()}"
    divider = "═" * 52
    thin = "─" * 52

    output = f"""{divider}
PROJECT REPORT
{report_title}
{divider}
Project:     {proj}
Prepared by: {prepared_by}
Date:        {date_str}
Report ID:   {report_id}
{thin}

1. EXECUTIVE SUMMARY
{thin[:20]}
{executive_summary}

2. OBJECTIVES
{thin[:13]}
{objectives}

3. METHODOLOGY
{thin[:14]}
{methodology}

4. FINDINGS
{thin[:11]}
{findings}

5. RECOMMENDATIONS
{thin[:18]}
{recommendations}

6. CONCLUSION
{thin[:13]}
{conclusion}

{divider}
End of Report
Generated by Hyperzod Document Agent
{date_str}
{divider}"""

    _last_generated["type"] = "report"
    _last_generated["content"] = output
    return output


# ---------------------------------------------------------------------------
# Tool 5 — generate_invoice
# ---------------------------------------------------------------------------

def generate_invoice(
    business_name: str,
    business_email: str,
    client_name: str,
    client_email: str,
    items: str,
    due_date: str = "",
    payment_method: str = "Bank Transfer",
    notes: str = "",
) -> str:
    """Generate a professional invoice with automatic totals.

    Args:
        business_name:   Name of the issuing business.
        business_email:  Business contact email.
        client_name:     Client or customer name.
        client_email:    Client email address.
        items:           Line items in format 'Name | qty | unit_price' per line.
        due_date:        Payment due date (default: 30 days from today).
        payment_method:  Accepted payment method.
        notes:           Additional notes for the client.

    Returns:
        Formatted invoice with computed totals as a string.
    """
    global _last_generated

    if not due_date:
        due_date = (datetime.now() + timedelta(days=30)).strftime("%d %B %Y")
    if not notes:
        notes = "Thank you for your business. Payment within due date is appreciated."

    invoice_number = f"INV-{datetime.now().strftime('%Y%m')}-{uuid.uuid4().hex[:4].upper()}"
    date_str = datetime.now().strftime("%B %d, %Y")
    divider = "═" * 62
    thin = "─" * 62

    # Parse items
    parsed_items = []
    subtotal = 0.0
    placeholder_used = False

    for line in items.strip().splitlines():
        line = line.strip()
        if not line:
            continue
        parts = [p.strip() for p in line.split("|")]
        try:
            if len(parts) >= 3:
                name = parts[0]
                qty = float(parts[1])
                unit_price = float(parts[2])
                line_total = qty * unit_price
                subtotal += line_total
                parsed_items.append((name, qty, unit_price, line_total))
            else:
                raise ValueError
        except (ValueError, IndexError):
            placeholder_used = True
            parsed_items.append(("[Item Description]", 1, 0.0, 0.0))

    if not parsed_items or placeholder_used:
        parsed_items = [
            ("Website Design", 1, 50000.0, 50000.0),
            ("SEO Setup", 1, 15000.0, 15000.0),
        ]
        subtotal = 65000.0

    tax = subtotal * 0.18
    total = subtotal + tax

    # Build items table
    header = f"{'DESCRIPTION':<32} {'QTY':>5} {'UNIT PRICE':>12} {'TOTAL':>10}"
    item_lines = []
    for name, qty, up, lt in parsed_items:
        item_lines.append(f"{name:<32} {qty:>5.0f} {'₹'+f'{up:,.2f}':>12} {'₹'+f'{lt:,.2f}':>10}")
    items_block = "\n".join(item_lines)

    output = f"""{divider}
INVOICE
{divider}
From: {business_name}
      {business_email}

To:   {client_name}
      {client_email}

Invoice No: {invoice_number}
Date:       {date_str}
Due Date:   {due_date}
{thin}

ITEMS
{thin[:5]}
{header}
{thin}
{items_block}
{thin}
{'Subtotal:':>50} {'₹'+f'{subtotal:,.2f}':>10}
{'GST (18%):':>50} {'₹'+f'{tax:,.2f}':>10}
{divider}
{'TOTAL DUE:':>50} {'₹'+f'{total:,.2f}':>10}
{divider}

Payment Method: {payment_method}

NOTES
{thin[:5]}
{notes}

{thin}
Generated by Hyperzod Document Agent
{date_str}
All amounts in INR (₹). Prices include applicable taxes."""

    _last_generated["type"] = "invoice"
    _last_generated["content"] = output
    return output


# ---------------------------------------------------------------------------
# Tool 6 — generate_email
# ---------------------------------------------------------------------------

def generate_email(
    email_type: str,
    sender_name: str,
    recipient_name: str = "Team",
    subject: str = "",
    context: str = "",
    tone: str = "professional",
) -> str:
    """Generate a professional email template.

    Args:
        email_type:     Type of email. Options: follow_up, job_application,
                        thank_you, meeting_request, project_update,
                        apology, cold_outreach.
        sender_name:    Name of the email sender.
        recipient_name: Name or title of the recipient.
        subject:        Email subject line (auto-generated if empty).
        context:        Additional context to customize the email body.
        tone:           Writing tone: professional, friendly, or formal.

    Returns:
        Formatted email template as a string.
    """
    global _last_generated

    # Greeting and closing based on tone
    tone_map = {
        "professional": (f"Hi {recipient_name},", "Best regards,"),
        "friendly":     (f"Hey {recipient_name}!", "Cheers,"),
        "formal":       (f"Dear {recipient_name},", "Yours sincerely,"),
    }
    greeting, closing = tone_map.get(tone, tone_map["professional"])

    # Email bodies keyed by type
    bodies = {
        "follow_up": {
            "subject": "Following Up — [Previous Discussion Topic]",
            "body": (
                f"I wanted to follow up on our recent conversation regarding [topic]. "
                f"I'm very interested in moving forward and would love to hear your thoughts.\n\n"
                f"Could you please update me on the current status? I'm happy to provide any "
                f"additional information or clarification that might be helpful.\n\n"
                f"Looking forward to your response."
            ),
        },
        "job_application": {
            "subject": f"Application for [Position] — {sender_name}",
            "body": (
                f"I am excited to apply for the [Position] role at [Company Name]. "
                f"With my background in [relevant field] and proven experience in [key skill], "
                f"I am confident I would be a strong addition to your team.\n\n"
                f"Please find my resume attached for your review. I would welcome the "
                f"opportunity to discuss how my skills align with your needs.\n\n"
                f"Thank you for your time and consideration."
            ),
        },
        "thank_you": {
            "subject": "Thank You — [Meeting/Opportunity Name]",
            "body": (
                f"Thank you so much for taking the time to meet with me regarding [topic/role]. "
                f"I truly appreciated the conversation and learning more about [specific point "
                f"discussed].\n\n"
                f"The discussion further confirmed my enthusiasm for this opportunity, and I am "
                f"very excited about the possibility of joining your team.\n\n"
                f"Please don't hesitate to reach out if you need any further information."
            ),
        },
        "meeting_request": {
            "subject": f"Meeting Request — {sender_name} / {recipient_name}",
            "body": (
                f"I hope this message finds you well. I would like to schedule a meeting to "
                f"discuss [purpose of meeting].\n\n"
                f"I am available at the following times:\n"
                f"• [Option 1: Day, Date, Time]\n"
                f"• [Option 2: Day, Date, Time]\n"
                f"• [Option 3: Day, Date, Time]\n\n"
                f"The agenda would include:\n"
                f"1. [Agenda item 1]\n"
                f"2. [Agenda item 2]\n"
                f"3. [Agenda item 3]\n\n"
                f"Please let me know what works best for you. Happy to adjust as needed."
            ),
        },
        "project_update": {
            "subject": "Project Update — [Project Name] | [Date]",
            "body": (
                f"Here is the latest update on [Project Name]:\n\n"
                f"✅ Completed:\n"
                f"• [Completed item 1]\n"
                f"• [Completed item 2]\n\n"
                f"🔄 In Progress:\n"
                f"• [In-progress item 1]\n"
                f"• [In-progress item 2]\n\n"
                f"⚠️ Blockers:\n"
                f"• [Blocker or risk — none if clear]\n\n"
                f"📅 Next Steps:\n"
                f"• [Next action item 1]\n"
                f"• [Next action item 2]\n\n"
                f"Please let me know if you have any questions or concerns."
            ),
        },
        "apology": {
            "subject": "Apologies Regarding [Issue]",
            "body": (
                f"I am writing to sincerely apologize for [specific issue]. "
                f"I understand this has caused inconvenience, and I take full responsibility.\n\n"
                f"We have taken the following steps to resolve the matter:\n"
                f"• [Resolution step 1]\n"
                f"• [Resolution step 2]\n\n"
                f"To prevent this from happening again, we are implementing [preventive measure]. "
                f"I value your trust and am committed to ensuring this does not recur.\n\n"
                f"Please accept my sincere apologies."
            ),
        },
        "cold_outreach": {
            "subject": f"Exploring Opportunities — {sender_name}",
            "body": (
                f"I came across [Company Name] and was impressed by [specific thing about them]. "
                f"I believe there could be a strong fit between my background and your needs.\n\n"
                f"I specialize in [your key value proposition] and have helped [type of clients] "
                f"achieve [specific result]. I'd love to explore whether I could bring similar "
                f"value to your team.\n\n"
                f"Would you be open to a brief 15-minute call this week or next?"
            ),
        },
    }

    email_data = bodies.get(email_type, bodies["follow_up"])
    if not subject:
        subject = email_data["subject"]

    body = email_data["body"]
    if context:
        body = f"[Context: {context}]\n\n" + body

    date_str = datetime.now().strftime("%B %d, %Y")
    divider = "═" * 52
    thin = "─" * 52
    type_label = email_type.replace("_", " ").title()

    output = f"""{divider}
EMAIL TEMPLATE — {type_label}
{divider}
To:      {recipient_name}
From:    {sender_name}
Subject: {subject}
{thin}

{greeting}

{body}

{closing}
{sender_name}

{thin}
[Customize bracketed placeholders before sending]
Generated by Hyperzod Document Agent"""

    _last_generated["type"] = "email"
    _last_generated["content"] = output
    return output


# ---------------------------------------------------------------------------
# Tool 7 — load_and_summarize
# ---------------------------------------------------------------------------

def load_and_summarize(
    content: str,
    filename: str = "document.txt",
    detail_level: str = "medium",
) -> str:
    """Load document content into memory and return a structured summary.

    Args:
        content:      The full text content of the document to load.
        filename:     Display name for the document.
        detail_level: Summary depth: 'brief', 'medium', or 'detailed'.

    Returns:
        Formatted summary with document statistics as a string.
    """
    global _document

    _document["filename"] = filename
    _document["content"] = content
    _document["loaded"] = True

    word_count = len(content.split())
    char_count = len(content)
    sentence_count = len([s for s in content.split(".") if s.strip()])
    para_count = len([p for p in content.split("\n\n") if p.strip()])

    thin = "─" * 49

    stats = (
        f"Words: {word_count} | Characters: {char_count}\n"
        f"Sentences: {sentence_count} | Paragraphs: {para_count}"
    )

    if detail_level == "brief":
        preview_words = content.split()[:150]
        preview = " ".join(preview_words)
        if word_count > 150:
            preview += " [...]"
        summary_body = preview

    elif detail_level == "detailed":
        preview_words = content.split()[:1000]
        preview = " ".join(preview_words)
        if word_count > 1000:
            preview += " [...]"
        paragraphs = [p.strip() for p in content.split("\n\n") if p.strip()]
        para_breakdown = "\n\n".join(
            f"Para {i+1}: {p.split('.')[0].strip()}."
            for i, p in enumerate(paragraphs[:6])
        )
        summary_body = preview + "\n\n--- PARAGRAPH BREAKDOWN ---\n" + para_breakdown

    else:  # medium (default)
        preview_words = content.split()[:400]
        preview = " ".join(preview_words)
        if word_count > 400:
            preview += " [...]"
        long_words = [w.lower().strip(".,;:!?") for w in content.split() if len(w) > 5]
        stopwords_ex = {"their", "there", "these", "those", "which", "about", "would", "could", "should"}
        unique_words = list(dict.fromkeys(w for w in long_words if w not in stopwords_ex))[:5]
        themes = ", ".join(unique_words) if unique_words else "[unable to extract]"
        summary_body = preview + f"\n\nKey themes identified: {themes}"

    output = (
        f"📄 DOCUMENT LOADED: {filename}\n"
        f"{thin}\n"
        f"{stats}\n"
        f"{thin}\n\n"
        f"{detail_level.upper()} SUMMARY\n"
        f"{thin[:24]}\n"
        f"{summary_body}\n\n"
        f"{thin}\n"
        f"✅ Document loaded. You can now:\n"
        f"• Ask questions about this document\n"
        f"• Ask me to edit or improve sections\n"
        f"• Export the content as formatted markdown"
    )

    return output


# ---------------------------------------------------------------------------
# Tool 8 — answer_from_document
# ---------------------------------------------------------------------------

def answer_from_document(question: str) -> str:
    """Answer a question using only the loaded document content.

    Performs keyword-based sentence scoring to find the most relevant
    passages. Does not use any external knowledge.

    Args:
        question: The question to answer from the document.

    Returns:
        Relevant sentences from the document as a formatted string.
    """
    global _document

    if not _document["loaded"]:
        return (
            "⚠️ No document loaded yet.\n"
            "Please paste your document content and I will load and "
            "summarize it first, then answer your questions."
        )

    stopwords = {
        "the", "a", "an", "is", "are", "was", "were", "in", "on", "at",
        "to", "for", "of", "and", "or", "but", "it", "this", "that",
        "with", "from", "by",
    }
    tokens = [
        w.lower().strip(".,;:!?")
        for w in question.split()
        if w.lower() not in stopwords
    ]

    sentences = [s.strip() for s in _document["content"].split(".") if s.strip()]

    scored = []
    for sent in sentences:
        sent_lower = sent.lower()
        score = sum(1 for t in tokens if t in sent_lower)
        if score > 0:
            scored.append((score, sent))

    scored.sort(key=lambda x: x[0], reverse=True)
    top = [s for _, s in scored[:5]]

    thin = "─" * 49
    filename = _document["filename"]

    if not top:
        return (
            f"The document does not contain information relevant to: '{question}'\n\n"
            f"Loaded document: {filename}"
        )

    answer_body = "\n\n".join(f"{s.strip()}." for s in top)

    return (
        f"🔍 ANSWER FROM DOCUMENT: {filename}\n"
        f"Question: {question}\n"
        f"{thin}\n\n"
        f"Based on the loaded document:\n\n"
        f"{answer_body}\n\n"
        f"{thin}\n"
        f"[Answer sourced from: {filename}]\n"
        f"[Only document content used — no external knowledge]"
    )


# ---------------------------------------------------------------------------
# Tool 9 — edit_and_improve
# ---------------------------------------------------------------------------

def edit_and_improve(
    content: str = "",
    improvement_type: str = "general",
    instruction: str = "",
) -> str:
    """Edit and improve provided content or the last generated document.

    Args:
        content:          Text to improve. Uses last generated doc if empty.
        improvement_type: Mode: general, formal, concise, professional, grammar.
        instruction:      Optional specific instruction to apply.

    Returns:
        Improved content with word count comparison as a string.
    """
    global _last_generated

    if not content:
        content = _last_generated.get("content", "")
    if not content:
        return (
            "No content to improve. "
            "Please provide content or generate a document first."
        )

    original_word_count = len(content.split())
    improved_content = content

    if improvement_type == "formal":
        replacements = {
            "I think": "I believe",
            "i think": "I believe",
            " get ": " obtain ",
            " use ": " utilize ",
            " show ": " demonstrate ",
            " help ": " assist ",
            " need ": " require ",
            " talk ": " discuss ",
            "find out": "ascertain",
            "Find out": "Ascertain",
        }
        for old, new in replacements.items():
            improved_content = improved_content.replace(old, new)

    elif improvement_type == "concise":
        verbose_map = {
            "in order to": "to",
            "due to the fact that": "because",
            "at this point in time": "now",
            "in the event that": "if",
            "for the purpose of": "for",
            "with regard to": "regarding",
            "in spite of the fact that": "although",
        }
        notes = []
        for verbose, concise in verbose_map.items():
            if verbose in improved_content.lower():
                notes.append(f'  • "{verbose}" → "{concise}"')
                improved_content = re.sub(
                    re.escape(verbose), concise, improved_content, flags=re.IGNORECASE
                )
        if notes:
            improved_content += (
                "\n\n[CONCISE NOTE: The following replacements were applied:]\n"
                + "\n".join(notes)
            )

    elif improvement_type == "professional":
        improved_content = (
            "[DOCUMENT PURPOSE: Professional communication document]\n\n"
            + improved_content
            + "\n\n[REVISION TRACKING: v1.0 — Initial draft]"
        )

    elif improvement_type == "grammar":
        lines = improved_content.split(". ")
        fixed = []
        for line in lines:
            line = line.strip()
            if line:
                line = line[0].upper() + line[1:]
                if not line.endswith((".", "!", "?")):
                    line += "."
            fixed.append(line)
        improved_content = " ".join(fixed)
        improved_content += (
            "\n\n[GRAMMAR NOTE: Sentences capitalized and punctuated. "
            "Please review their/there/they're and its/it's usage manually.]"
        )

    else:  # general
        improved_content = (
            "[GENERAL IMPROVEMENT APPLIED]\n\n"
            + improved_content
            + "\n\n[EDITORIAL NOTES]\n"
            "• Review all [BRACKETED] placeholders and replace with specific content.\n"
            "• Ensure consistent tense throughout the document.\n"
            "• Verify contact details and dates are accurate.\n"
            "• Proofread for flow and tone before sharing."
        )

    improved_word_count = len(improved_content.split())
    thin = "─" * 49

    instruction_line = ""
    if instruction:
        instruction_line = f"\nApplied instruction: {instruction}"

    output = (
        f"✏️ IMPROVED DOCUMENT ({improvement_type.title()} Mode)\n"
        f"{thin}\n"
        f"Original: {original_word_count} words\n"
        f"Improved: {improved_word_count} words\n"
        f"{thin}\n\n"
        f"{improved_content}\n\n"
        f"{thin}"
        f"{instruction_line}\n"
        f"[Review all [BRACKETED] notes before finalizing]"
    )

    _last_generated["type"] = _last_generated.get("type", "edited")
    _last_generated["content"] = improved_content
    return output


# ---------------------------------------------------------------------------
# Tool 10 — export_as_markdown
# ---------------------------------------------------------------------------

def export_as_markdown(
    content: str = "",
    document_title: str = "",
) -> str:
    """Export content or the last generated document as clean markdown.

    Args:
        content:        Text to export. Uses last generated doc if empty.
        document_title: Title for the markdown document. Auto-detected if empty.

    Returns:
        Full export output including BEGIN/END markers as a string.
    """
    global _last_generated

    if not content:
        content = _last_generated.get("content", "")
    if not content:
        return "No content to export."

    if not document_title:
        type_map = {
            "cv": "Curriculum Vitae",
            "cover_letter": "Cover Letter",
            "proposal": "Business Proposal",
            "report": "Project Report",
            "invoice": "Invoice",
            "email": "Email Template",
            "edited": "Improved Document",
        }
        document_title = type_map.get(_last_generated.get("type", ""), "Document")

    date_str = datetime.now().strftime("%B %d, %Y")

    # Convert plain-text formatting to markdown
    lines = content.splitlines()
    md_lines = []
    for line in lines:
        stripped = line.strip()
        # Divider lines
        if re.match(r"^[═─]{4,}$", stripped):
            md_lines.append("---")
        # ALL CAPS headings (min 3 chars, no digits)
        elif (
            stripped.isupper()
            and len(stripped) >= 3
            and not stripped.startswith("INV-")
            and not stripped.startswith("RPT-")
            and not stripped.startswith("PROP-")
        ):
            md_lines.append(f"## {stripped.title()}")
        # Bullet points
        elif stripped.startswith("• "):
            md_lines.append("- " + stripped[2:])
        # Numbered lists already fine
        elif re.match(r"^\d+\.", stripped):
            md_lines.append(stripped)
        else:
            md_lines.append(line)

    md_body = "\n".join(md_lines)

    # Header and footer
    header = (
        f"# {document_title}\n"
        f"> Generated by Hyperzod Document Agent on {date_str}\n\n---\n"
    )
    footer = (
        "\n---\n"
        f"*Document generated by Hyperzod Document Agent*  \n"
        f"*Export date: {date_str}*"
    )

    full_md = header + md_body + footer
    word_count = len(full_md.split())
    thin = "─" * 49

    output = (
        f"✅ MARKDOWN EXPORT READY\n"
        f"{thin}\n"
        f"Copy everything between the markers below:\n\n"
        f"═══ BEGIN MARKDOWN ═══\n\n"
        f"{full_md}\n\n"
        f"═══ END MARKDOWN ═══\n\n"
        f"{thin}\n"
        f"{word_count} words | Ready to paste into Notion, GitHub, or any markdown editor."
    )

    return output

